### ISSUE TITLE
Rethink and rework required channel alias permissions

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/beerchat#102]
Admin privilege should be used to bypass all possible checks, maybe even special channel protection.

Moderator privilege should probably just check if player has access to both channels, currently it checks if player is owner of both channels.

**Comment by SwissalpS** [comment]
So if player A created #español but isn't active anymore but channel is being used and now they want an alias #castellano only admin could do that?  
Since Player B is owner of #castellano?

**Comment by S-S-X** [comment]
> So if player A created #español but isn't active anymore but channel is being used and now they want an alias #castellano only admin could do that?
> Since Player B is owner of #castellano?

Currently it is like that. And even then only with `ban` privilege.

So I was thinking making it work like this:
* If player is admin then he can link any channels, no matter what.
* If player is moderator then he can link any channels he can normally access.
* And maybe allow any player to alias channel if they own both channels, source and target.
