### ISSUE TITLE
What is the license for source code?

### ISSUE THREAD

**Issue by Panquesito7** [mt-mods/beerchat#117]
### Description

On the README, it says the license is GPLv3.0.
But the LICENSE file itself is LGPLv3.0? I know the LGPLv3.0 contains a set of additional permissions based on GPLv3.0, but I think we should specify the actual license.

**Comment by S-S-X** [comment]
README.md on the other hand is a mistake / typo: https://github.com/mt-mods/beerchat/commit/5cd4ee8d1a0ee1108fed2b367fa5b56b4f69f478

**Comment by Panquesito7** [comment]
I believe it should be fixed, then.

**Comment by BuckarooBanzay** [comment]
thanks for spotting that :+1:
