### ISSUE TITLE
Allow admin, or ... special to delete channels

### ISSUE THREAD

**Issue by Festus1965** [mt-mods/beerchat#50]
As I found a lot of mistaken channels created by an over a year no online gamer, 
I wanted to clean up, but ...

So like at the mod
chatcommands.lua
local delete_channel
guess behind line ff105
`if name ~= beerchat.channels[param].owner then
    return false, "ERROR: You are not the owner of channel " .. param
end`
like
`if name == "admin" then -- or use admin value of minetest .conf?
return true
end`
to let a special person clean up

**Comment by S-S-X** [comment]
Checking for some chat administration privilege would probably be best option here.

* `basic_privs` can revoke `shout` and might fit here too but if I would make decision then probably would not use that?
* Possibly `ban` privilege which is used for other stuff and is normally granted only for trusted players, without thinking too much I'd probably go with this one.
* Or new privilege could be added for more control over who can manage channels that he does not own.
