### ISSUE TITLE
sound assets license issue

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/beerchat#73]
Looks like they aren't free after all: https://www.soundboard.com/sb/sound/450659

CC @waxtatect

**Comment by S-S-X** [comment]
>  Personal
> Boards listed with 'Personal' rights include sounds that can be used for anything that does NOT result in financial gain. This can include (but not necessarily be limited to) school activities, personal enjoyment, shows, events, parties, plays, etc.

What all this exactly means I do not know, TOS TLDR but seems that it might give license that is somewhat similar to CC-NC but with additional restrictions.
https://www.soundboard.com/terms.aspx

> You also hereby grant each user of the Soundboard Website a non-exclusive license to access your User Submissions through the Website, and to use, reproduce, distribute, prepare derivative works of, display and perform such User Submissions as permitted through the functionality of the Website

Like said, at first glance it seems like it _might_ be fine but it is not that simple. Would need to study whole TOS in depth to understand it and possibly also go through other material.

Of course one option would be to ask for permission / license by emailing them... sometimes that works but would need to find out correct recipient.

**Comment by BuckarooBanzay** [comment]
> Of course one option would be to ask for permission / license by emailing them... sometimes that works but would need to find out correct recipient.

I think just replacing the assets with free ones would be _way_ faster :wink:

**Comment by OgelGames** [comment]
Worth noting here that these sounds are from Star Trek (The Original Series), and can be downloaded from other websites (e.g. https://www.trekcore.com/audio/), so this is not about Soundboard, but whether we can use sound effects from a 1966 television series.
