### ISSUE TITLE
server logs & chat channel

### ISSUE THREAD

**Issue by MCLV-pandorabox** [mt-mods/beerchat#76]
It can't be gleaned from the server logs who's talking in what channel.
From an information gathering perspective (ie staff/moderator) this is desirable.

**Comment by BuckarooBanzay** [comment]
looks those `ACTION[server] CHAT` messages are coming from the engine: https://github.com/minetest/minetest/blob/4cd6b773bb5de2594c682ae7e5793c80ad6a22e6/src/server.cpp#L3072 and not even the mod itself...
